### PR TITLE
Updates all templates to use ember-let instead of `with`.

### PR DESCRIPTION
**Pull request by patrickberkeley**
@taras this is to address: https://github.com/LocusEnergy/ember-sparkles/issues/42.

Let me know if you were looking for anything else there.

### CODE REVIEW

**Comment by taras** [comment]
We're going to start working on this soon and we'll get this merged in. Thank you for doing this :)

**Comment by ghost** [comment]
@patrickberkeley this looks great! What about using inline `let` where we can?

**Comment by patrickberkeley** [comment]
@zigahertz would you mind commenting with an example? I'm not seeing attributes in the components that could be eliminated with let.

**Comment by ghost** [comment]
@patrickberkeley I meant, using the inline let as described here - https://github.com/thefrontside/ember-let

Not to eliminate attributes, just to clean up the templates more (it allows for one less level of indentation)

**Comment by patrickberkeley** [comment]
@zigahertz gotcha. I've added a commit that uses the inline syntax: https://github.com/LocusEnergy/ember-sparkles/pull/51/commits/8d3f52ec7b572dcfcebfe32c08ecad35dd99db9c

Note, I needed to use version 0.4.0 of `ember-let` in order to get this working. With anything newer, I'd get errors on [this line](https://github.com/thefrontside/ember-let/blob/master/vendor/ember-let/register.js#L35). It looks like somehow `ember-let` thinks I'm using the block syntax.

**Comment by ghost** [comment]
@patrickberkeley interesting, thanks for trying this out... @taras as one of the authors of `ember-let`, any thoughts on this?

**Comment by patrickberkeley** [comment]
@zigahertz I merged in your recent updates and gave `ember-let` 0.5.3 another shot. I get a different error now, so still no 🎲🎲 . The inline `let` variables seem like they aren't being defined because – for example – the `compute` helper complains `TypeError: Cannot read property 'apply' of undefined` [here](https://github.com/LocusEnergy/ember-sparkles/pull/51/files#diff-96c3eb164476c32c443d1119307c3c1fR25).

**Comment by yarigpopov** [comment]
@patrickberkeley feels like something incompatibility with ember v2.10
I have the same error for grouped-chart

**Comment by zigahertz** [comment]
@patrickberkeley @chilicoder I see - @taras and I did some investigation a little while ago - we think the issue lies exactly where you pointed, at https://github.com/LocusEnergy/ember-sparkles/pull/51/files#diff-96c3eb164476c32c443d1119307c3c1fR25 - the solution might be to just re-work that `compute` logic for the scale functions, which is a bit too nested at this point. I think handling that logic using `let` within the parent scope might be the solution. I am (mostly) on vacation until the second week of January, if I get some free time I will try to outline my idea more clearly and push a PR. Otherwise, if this makes sense - please feel free to give it a shot. If not, please feel free to ask questions here or send me a DM in the Ember community Slack.

**Comment by ghost** [comment]
@patrickberkeley @chilicoder I see - @taras and I did some investigation a little while ago - we think the issue lies exactly where you pointed, at https://github.com/LocusEnergy/ember-sparkles/pull/51/files#diff-96c3eb164476c32c443d1119307c3c1fR25.

I think the solution is to upgrade the library to use Ember 2.10. This breaks because of the `compute` logic for the scale functions, it's too nested and needs to be refactored. This is where `let` in the parent scope might be quite handy. I am (mostly) on vacation until the second week of January, if I get some free time I will try to outline my idea more clearly and push a PR. Otherwise, if this makes sense - please feel free to give it a shot. If not, please feel free to ask questions here or send me a DM in the Ember community Slack.

**Pull request merged**
