### PR TITLE
Update the library for ember 2.17

### PR DESCRIPTION
**Pull request by yarigpopov**
Hi!

Here is my update for the library to make it possible to use from Ember 2.16+ versions

### CODE REVIEW

**Comment by yarigpopov** [comment]
Ok.. here I have to pause(.  
tests are red due to the error `TypeError: compileArgs is not a function`  which is a problem for 
`ember-let` library  (see  issue https://github.com/thefrontside/ember-let/issues/44 for details)
We need PR https://github.com/thefrontside/ember-let/pull/43 to close to make tests green.

**Comment by yarigpopov** [comment]
small update. We need this PR to be merged https://github.com/thefrontside/ember-let/pull/45

**Comment by ghost** [comment]
I will merge this today

**Comment by ghost** [comment]
I merged with the failing tests and added the new `ember-let` version (as well as the updated `ember-d3-helpers`). Travis is failing because we don't have `yarn` support, it looks like - would you be up for taking a look? I don't have much more time to spend on this today. As mentioned in d3 helpers - would be happy to add you as a maintainer, if you are interested! I really appreciate the pull requests you've been contributing.

**Comment by yarigpopov** [comment]
Hi @zigahertz 
Thank you for the merge!  Also good news from ember-let repo!, Guys merged PR for ember 2.15+ support tonight (but still wait while it will be published in npm). 

I will wait while ember-let 0.7 will appear in npm and then proceed with fixing travis CI builds. 

I really appreciate your affords for this library and also for`ember-d3-helpers`. Would be nice for me to be included in maintainers, since I rely on them in my current projects.

**Pull request merged**
